version: "3"

services: 
    colab:
        build:  
            context: .
            dockerfile: Dockerfile
        ports: 
            - 3002:3002
        command: npm start --port=3002
        volumes: 
            - .:/app