version: "3"

services: 
    colab:
        build:  
            context: .
            dockerfile: Dockerfile
        ports: 
            - 3000:3001
        command: npm start
        volumes: 
            - .:/app